### ISSUE TITLE
installation: workflow controller only runs when installed with editable mode

### ISSUE THREAD

**Issue by diegodelemos** [reanahub/reana-workflow-controller#160]
Working on [current master](https://github.com/reanahub/reana-workflow-controller/commit/387041409bd16ba7b430599304a10c8571a94ba3):
```console
$ pip install -e .
$ export FLASK_APP=reana_workflow_controller/app.py
$ flask run --host=0.0.0.0
 * Serving Flask app "reana_workflow_controller/app.py"
 * Environment: production
   WARNING: Do not use the development server in a production environment.
   Use a production WSGI server instead.
 * Debug mode: off
 * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
$ pip install .
$ flask run --host=0.0.0.0
 * Serving Flask app "reana_workflow_controller/app.py"
 * Environment: production
   WARNING: Do not use the development server in a production environment.
   Use a production WSGI server instead.
 * Debug mode: off
Usage: flask run [OPTIONS]

Error: While importing "reana_workflow_controller.app", an ImportError was raised:

Traceback (most recent call last):
  File "/Users/rodrigdi/.virtualenvs/r-w-controller/lib/python3.6/site-packages/flask/cli.py", line 235, in locate_app
    __import__(module_name)
  File "/Users/rodrigdi/.virtualenvs/r-w-controller/lib/python3.6/site-packages/reana_workflow_controller/app.py", line 17, in <module>
    app = create_app()
  File "/Users/rodrigdi/.virtualenvs/r-w-controller/lib/python3.6/site-packages/reana_workflow_controller/factory.py", line 28, in create_app
    from .rest import restapi_blueprint  # noqa
  File "/Users/rodrigdi/.virtualenvs/r-w-controller/lib/python3.6/site-packages/reana_workflow_controller/rest.py", line 45, in <module>
    from reana_workflow_controller.workflow_run_managers.kubernetes import \
ModuleNotFoundError: No module named 'reana_workflow_controller.workflow_run_managers'
```
This has not been spotted because of running on [DEBUG mode](https://github.com/reanahub/reana-workflow-controller/blob/master/Dockerfile#L25) with `docker build --build-arg DEBUG=true . -t reanahub/reana-workflow-controller:latest`.

**Comment by tiborsimko** [comment]
BTW looking at the file structure, the code seems to live mostly inside `__init__.py` files:

```console
$ find reana_workflow_controller/workflow_run_managers  
reana_workflow_controller/workflow_run_managers
reana_workflow_controller/workflow_run_managers/__init__.py
reana_workflow_controller/workflow_run_managers/kubernetes
reana_workflow_controller/workflow_run_managers/kubernetes/__init__.py
```

Personally I prefer to keep `__init__.py` files very small (even blank!) and the logic living rather in "visible" `app.py`, `rest.py` and friends and the imports are then made explicit.

Quoting from https://docs.python-guide.org/writing/structure/:

    A commonly seen issue is to add too much code to __init__.py files. 
    When the project complexity grows, there may be sub-packages and 
    sub-sub-packages in a deep directory structure. In this case, importing 
    a single item from a sub-sub-package will require executing all __init__.py 
    files met while traversing the tree.
    
What about refactoring it?
