### ISSUE TITLE
travis: enabling the cache when installing requirements builder

### ISSUE THREAD

**Issue by dinosk** [reanahub/reana-workflow-controller#173]
After Travis started failing with:
```
Exception:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/pip/_internal/cli/base_command.py", line 176, in main
    status = self.run(options, args)
  File "/usr/local/lib/python2.7/site-packages/pip/_internal/commands/install.py", line 346, in run
    session=session, autobuilding=True
  File "/usr/local/lib/python2.7/site-packages/pip/_internal/wheel.py", line 848, in build
    assert building_is_possible
AssertionError
The command '/bin/sh -c pip install --no-cache-dir requirements-builder &&     requirements-builder -e all -l pypi setup.py | pip install --no-cache-dir -r /dev/stdin &&     pip uninstall -y requirements-builder' returned a non-zero code: 2
The command "./run-tests.sh" exited with 2.
```

removing the `--no-cache-dir` from the Dockerfile fixed the issue, described in https://github.com/pypa/pip/blame/master/src/pip/_internal/wheel.py#L843.
Note that if the cache creates problems in the future, or the TODO is addressed, it could be added back.

**Comment by diegodelemos** [comment]
To revert https://github.com/reanahub/reana-job-controller/pull/108 and check if Travis now works.
