### ISSUE TITLE
runaway `NotReady` pods for wrong compute backends

### ISSUE THREAD

**Issue by tiborsimko** [reanahub/reana-workflow-controller#401]
When a user asks to run some non-supported workflow engine, such as:

```console
$ reana-client run -f ./reana-cwl-slurmcern.yaml
```

Then the workflow fails:

```console
$ reana-client status -w workflow.4
NAME       RUN_NUMBER   CREATED               STARTED               ENDED                 STATUS   PROGRESS
workflow   4            2021-10-05T14:20:12   2021-10-05T14:20:24   2021-10-05T14:20:28   failed   0/2  
```

but the pod keeps running away in a `NotReady` state:

```console
$ kubectl get pods | grep NotReady           
reana-run-batch-efe4cd5a-eb74-401b-9359-9158394f62ab-5qkh4   1/2     NotReady   0          6m15s
```

The error logs show:

```console
$ kubectl logs  reana-run-batch-efe4cd5a-eb74-401b-9359-9158394f62ab-5qkh4 job-controller
...
2021-10-05 14:20:24,682 | werkzeug | Thread-1 | INFO | 127.0.0.1 - - [05/Oct/2021 14:20:24] "GET /jobs HTTP/1.1" 200 -
2021-10-05 14:20:28,260 | root | Thread-2 | ERROR | Job submission failed. Backend slurmcern is not supported.
NoneType: None
2021-10-05 14:20:28,260 | root | Thread-2 | INFO | Storing workflow logs: efe4cd5a-eb74-401b-9359-9158394f62ab
2021-10-05 14:20:28,304 | werkzeug | Thread-2 | INFO | 127.0.0.1 - - [05/Oct/2021 14:20:28] "POST /jobs HTTP/1.1" 500 -
```

and:

```console
$ kubectl logs reana-run-batch-efe4cd5a-eb74-401b-9359-9158394f62ab-5qkh4 workflow-engine
[job gendata] Failed to submit task to job controller:
Job submission error: 
2021-10-05 14:20:28,305 | reana-workflow-engine-cwl | MainThread | ERROR | [job gendata] Failed to submit task to job controller:
Job submission error: 
Traceback (most recent call last):
  File "/code/modules/reana-commons/reana_commons/api_client.py", line 163, in submit
    response, http_response = self._client.jobs.create_job(
  File "/usr/local/lib/python3.8/site-packages/bravado/http_future.py", line 271, in result
    swagger_result = self._get_swagger_result(incoming_response)
  File "/usr/local/lib/python3.8/site-packages/bravado/http_future.py", line 124, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/bravado/http_future.py", line 299, in _get_swagger_result
    unmarshal_response(
  File "/usr/local/lib/python3.8/site-packages/bravado/http_future.py", line 333, in unmarshal_response
    raise_on_unexpected(incoming_response)
  File "/usr/local/lib/python3.8/site-packages/bravado/http_future.py", line 404, in raise_on_unexpected
    raise make_http_exception(response=http_response)
bravado.exception.HTTPInternalServerError: 500 INTERNAL SERVER ERROR

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/reana_workflow_engine_cwl/cwl_reana.py", line 354, in run
    task_id = runtimeContext.pipeline.service.submit(**task)
  File "/code/modules/reana-commons/reana_commons/api_client.py", line 169, in submit
    raise REANAJobControllerSubmissionError(msg)
reana_commons.errors.REANAJobControllerSubmissionError: Job submission error: 

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/reana_workflow_engine_cwl/pipeline.py", line 93, in executor
    runnable.run(runtimeContext)
  File "/usr/local/lib/python3.8/site-packages/reana_workflow_engine_cwl/cwl_reana.py", line 370, in run
    raise WorkflowException(e)
cwltool.errors.WorkflowException: Job submission error: 
ERROR Workflow error, try again with --debug for more information:
Job submission error: 
```

We should reply back to user that `slurmcern` is not supported compute backend and the run-batch pod should terminate properly instead of running away.

P.S. CWL was just an example, we get the same problem for Yadage workflow engine for example. 

_Originally posted by @tiborsimko in https://github.com/reanahub/reana-workflow-engine-cwl/pull/207#discussion_r722294643_

**Comment by VMois** [comment]
After investigation, pods are staying in the `NotReady` status due to `REANA_RUNTIME_KUBERNETES_KEEP_ALIVE_JOBS_WITH_STATUSES` env variable in `reana/helm/configurations/values-dev.yaml`. So this issue occurs only in local testing setup.

**Comment by VMois** [comment]
Some small improvements can be done like: changing response HTTP status from `500` to `404` in `job-controller`, add warning in case `REANA_RUNTIME_KUBERNETES_KEEP_ALIVE_JOBS_WITH_STATUSES` is used, etc.

**Comment by tiborsimko** [comment]
@audrium Yes, we have discussed live that if we filter unsupported combinations at the front-end, we don't have to do anything here... So basically this issue can be "worked around" before at the input sanitising level. This seems better than start changing 500 etc here. We can keep the issue and close it "elsewhere", or close this issue and create new one "elsewhere" for input sanitisation.

(BTW a note about motivation. Note that sometimes we are running production-like clusters with `failed` enabled, so that failed user job pods would stay, so that we could more easily debug what went wrong. However, this need will happily disappear once we shall work on the live logs feature, when the job pods would stream stdout/stderr during pod lifetime. When we have live logs done, this will also eliminate needs for production-like deployments with `failed` set on.)

**Comment by tiborsimko** [comment]
The users are informed about why the job failed, which is good! But the issue is still there for those installations that use `REANA_RUNTIME_KUBERNETES_KEEP_ALIVE_JOBS_WITH_STATUSES`. It can be prevented in either case by sanitising arguments upfront, as mentioned above. If you prefer, I can create a new dedicated issue for the sanitisation.
