### ISSUE TITLE
mq: message queue consumer failure

### ISSUE THREAD

**Issue by diegodelemos** [reanahub/reana-workflow-controller#88]
We should start the MQ consumer in a different pod to take benefit from Kubernetes  deployment retry (now it fails because some times RabbitMQ is still not deployed).

```console
$ kubectl logs workflow-controller-7cb4bb96cd-5xwwr
00000000-0000-0000-0000-000000000000
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.6/site-packages/reana_workflow_controller/app.py", line 47, in run
    consume_job_queue()
  File "/usr/local/lib/python3.6/site-packages/reana_workflow_controller/tasks.py", line 77, in consume_job_queue
    broker_credentials))
  File "/usr/local/lib/python3.6/site-packages/pika/adapters/blocking_connection.py", line 374, in __init__
    self._process_io_for_connection_setup()
  File "/usr/local/lib/python3.6/site-packages/pika/adapters/blocking_connection.py", line 414, in _process_io_for_connection_setup
    self._open_error_result.is_ready)
  File "/usr/local/lib/python3.6/site-packages/pika/adapters/blocking_connection.py", line 468, in _flush_output
    raise exceptions.ConnectionClosed(maybe_exception)
pika.exceptions.ConnectionClosed: Connection to 10.106.116.239:5672 failed: [Errno 111] Connection refused

 * Serving Flask app "reana_workflow_controller/app.py"
 * Environment: production
   WARNING: Do not use the development server in a production environment.
   Use a production WSGI server instead.
 * Debug mode: off
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.6/site-packages/reana_workflow_controller/app.py", line 47, in run
    consume_job_queue()
  File "/usr/local/lib/python3.6/site-packages/reana_workflow_controller/tasks.py", line 77, in consume_job_queue
    broker_credentials))
  File "/usr/local/lib/python3.6/site-packages/pika/adapters/blocking_connection.py", line 374, in __init__
    self._process_io_for_connection_setup()
  File "/usr/local/lib/python3.6/site-packages/pika/adapters/blocking_connection.py", line 414, in _process_io_for_connection_setup
    self._open_error_result.is_ready)
  File "/usr/local/lib/python3.6/site-packages/pika/adapters/blocking_connection.py", line 468, in _flush_output
    raise exceptions.ConnectionClosed(maybe_exception)
pika.exceptions.ConnectionClosed: Connection to 10.106.116.239:5672 failed: [Errno 111] Connection refused
```

**Comment by diegodelemos** [comment]
Closed by https://github.com/reanahub/reana-cluster/pull/88.
